### ISSUE TITLE
Moved positions incorrectly.

### ISSUE THREAD

**Issue by itsnotaboutthecell** [mogular/powerquery-formatter-examples#1]
**Description**
Formatter incorrectly moved position of underlying M and caused an error.

**Power Query- / M-Code**
(#"Input Value" as text, Like as logical) as any =>
let
    Values = {
                {"Aus","Australia"},
                {"Palestin", "Palestine"},
                {"Macao", "Macau"},
                {"Congo","Republic of the Congo"},
                {"Taiwan", "Taiwan"},
                {"Verde","Cabo Verde"},
                {"Hong Kong","Hong Kong"},
                {"Iran","Iran"},
                {"China","China"},
                {"Moldova","Moldova"},
                {"Bahamas","Bahamas"},
                {"Gambia","Gambia"},
                {"UK","United Kingdom"},
                {"US","United States"},
                {"Viet Nam","Vietnam"},
                {"South","South Korea"},
                {"Czech","Czech Republic"},
                {"Ship", null},
                {"Princess", null},
                {"The", null}
    },
    SWITCH = List.First(
        List.Select(
            Values, 
            each if Like 
                    then Text.Contains(#"Input Value", _{0}, Comparer.OrdinalIgnoreCase) 
                    else _{0} = #"Input Value"
        )
    ){1}?,
    Result = if SWITCH = null then #"Input Value" else SWITCH
in
    Result

**Expected behavior**
Original: {1}?
Formatter: {? 1}

**Settings**
Nothing.

**Comment by UliPlabst** [comment]
I just fixed this, thanks for the report!
