### ISSUE TITLE
Valid code can't be parsed

### ISSUE THREAD

**Issue by AmeliaSZK** [mogular/powerquery-formatter-examples#13]
**Description**
In the web formatter, my valid M code couldn't be parsed, and I was told the error was likely to be in my code. I know the code is correct because it works in Power Query for Excel.

**Power Query- / M-Code**
```
let
    FormatTagForTitling = (
        tag as nullable text
    ) as nullable text => 
    if tag is null then tag else
    let
        ReplacedUnderscores = Text.Replace(tag, "_", " "),
        Capitalized = Text.Proper(ReplacedUnderscores),

        Returned = Capitalized
    in
        Returned,

    DocumentedCall = FormatTagForTitling
in
    DocumentedCall
```

**Expected behavior**
Format without returning an error.

**Settings**
All defaults.

This error happened both in Chrome and Firefox.

**Error message**
```
Errors occured
We use the official microsoft powerquery-parser so chances are that the issue is within your code.
Inner Error
{
   "innerError": {
      "invariantBroken": "Ast maybeChildIds !== undefined",
      "maybeDetails": {
         "childIds": [
            10
         ],
         "nodeId": 8
      }
   }
}
Meta Info
null
```

**Comment by UliPlabst** [comment]
After debugging this issue I found that the official powerquery parser throws the error you're seeing. As the parser is under development an update of the parser library might fix the issue. Unfortunately this requires some more work as interfaces changed. I don't have any more time today but I'll see if I can invest some time in the upcoming days

**Comment by UliPlabst** [comment]
closed acciedentally...

**Comment by UliPlabst** [comment]
I just upgraded the parser library to the newest version but the problem persists. I filed a bug report in the parser repo.

**Comment by UliPlabst** [comment]
This bug was fixed in the parser library and the issue with the formatter is resolved :)
