### ISSUE TITLE
How to get the formatted text with python

### ISSUE THREAD

**Issue by jasonlaw997** [mogular/powerquery-formatter-examples#16]
requests.post('https://m-formatter.azurewebsites.net/api/format/v2', data=json.dumps(m_text),timeout=15)

It responds 404

**Comment by UliPlabst** [comment]
Hi, your request url seems to be wrong. You need to use `https://m-formatter.azurewebsites.net/api/v2` (drop the /format). While our v1 api used the /format path we dropped it for v2 to be able to have one azure function for each version. You cann still use /format/v1 for version v1 but for version v2 you have to drop it.

**Comment by UliPlabst** [comment]
I just saw that the /format was present in the api documentation. Sorry about that, I just removed it.
