### ISSUE TITLE
Could not parse code

### ISSUE THREAD

**Issue by gustavoleo** [mogular/powerquery-formatter-examples#2]
**Description**

Es sind Fehler aufgetreten
Could not parse code
Could not parse your M code. We use the official microsoft powerquery-parser so chances are that the issue is within your code.
Inner Error
{
   "innerError": {
      "graphemePosition": {
         "characterCodeUnitIndex": 666,
         "lineNumber": 7,
         "columnNumber": 101
      }
   }
}
Meta Info
null

**Power Query- / M-Code**
The code you wanted to formatted but that triggered your bug i.e. was not formatted properly.
[m code.txt](https://github.com/mogular/powerquery-formatter-examples/files/4536300/m.code.txt)

**Settings**
Special configuration settings you possibly used to call the formatter.

**Comment by UliPlabst** [comment]
I just fixed this. Thanks for the report!
