### ISSUE TITLE
Section documents not supported

### ISSUE THREAD

**Issue by CurtHagenlocher** [mogular/powerquery-formatter-examples#3]
**Description**
I used the web formatter.

**Power Query- / M-Code**
section S; shared Q = 1;

**Expected behavior**
section S;

shared Q = 1;

**Settings**
N/A

Ich wollte sehen ob euer Parser auch ein "section document" versteht. Leider ging es nicht. Übrigens gibt es auf GitHub ein Open Source Parser für M in TypeScript bei https://github.com/Microsoft/powerquery-parser.

**Comment by UliPlabst** [comment]
Hi, wir planen section documents in Zukunft zu unterstützen. Leider haben wir uns im Moment nur auf die einzelnen Queries beschränkt. Sobald ich Zeit habe die Sections zu implementieren geb ich dir bescheid.

**Comment by UliPlabst** [comment]
Btw. we are already using the official powerquery parser that you linked to retrieve the code AST but thanks for the recommendation.

**Comment by UliPlabst** [comment]
Danke für den Link, tatsächlic hbenutzen wir schon diesen offiziellen powerquery parser und formattieren dann auf Basis des AST

**Comment by UliPlabst** [comment]
Also ich habe versucht sections einzubauen. Der Formatter versteht jetzt eine section und section members. Leider kann der powerquery-parser von ms keine Multi-Section-Dokumente parsen und auch keine SectionAccessExpression. Ich habe [hier](https://github.com/microsoft/powerquery-parser/issues/155) eine Issue in deren repo gestellt. Ich denke dort wird diskutiert, ob multi sections tatsächlich Teil der Language sind.   
Ich schau mal ob die das in Zukunft fixen, ansonsten würde ich das in ein paar wochen evtl. selber dazubauen.

**Comment by UliPlabst** [comment]
Closing this as the official [powerquery language specification](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar) since has changed to not allow multiple sections in one document.
