### ISSUE TITLE
Valid M Syntax is changed in invalid one after formatting

### ISSUE THREAD

**Issue by marcosqlbi** [mogular/powerquery-formatter-examples#6]
This expression is valid M code that once formatted produces an invalid syntax

Original code:
= Table.SelectRows(#"Merged Queries", each [Attributes]?[Hidden]? <> true)

Formatted code:
= Table.SelectRows(
    #"Merged Queries", 
    each [? Attributes][? Hidden] <> true
  )

**Comment by UliPlabst** [comment]
Thanks for the report, I will fix this tomorrow.

**Comment by UliPlabst** [comment]
I just uploaded the fix. If any additional issues occur please let me know.
