### ISSUE TITLE
Wrong tooltip?

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [mogular/powerquery-formatter-examples#7]
**Description**
-
web formatter - Options section.
The tooltip text for the _'Align paired expressions by equal'_ checkbox seems wrong.

**Power Query- / M-Code**
-

**Expected behavior**
-
A more appropriate text describing the function of the checkbox.

**Settings**
-

**Comment by UliPlabst** [comment]
You're right it was a copy paste bug. I just uploaded the fix. Thanks for the report.
